name: Continuous Integration
run-name: running test on GitHub image
on: 
  workflow_dispatch:
  push:
    branches: 
     - singhjyoti
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      # Install a chromium browser in the runner
      - name: Install Chromium
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with: 
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Run E2E test
        run: npm run wdio
      - name: Publishing artifacts
        uses: actions/upload-artifact@v3.2.1-node20
        if: failure()
        with:
          name: logs
          path: logs
