name: GitHub Actions Demo
run-name: running test on GitHub image
on: 
  push:
    branches: 
     - singhjyoti010
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with: 
          node-version: 20
      - name: npm install
        run: npm install
      - name: Run script
        run: npm run wdio
      - name: Publishing artifacts
        uses: actions/upload-artifact@v3.2.1-node20
        if: failure()
        with:
          name: logs
          path: logs
